### ISSUE TITLE
http://portal.prattle.co/auth/local/ not found

### ISSUE THREAD

**Issue by FXLab91** [prattle-analytics/prattle_api_guide#1]
As of this afternoon I am not able to authenticate via the [https://portal.prattle.co/auth/local/](https://portal.prattle.co/auth/local/) and I get a "Not found error". The same script worked in the past so I am a bit confused.

I tried the autentication from the cmd line using the example reported and I got:

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>

**Comment by wmacmillan** [comment]
Thanks for flagging this. We had a minor hiccup as we've been working to upgrade to https. We'll be implement full time https at the end of business of Friday the 29th. We should be operating as normal at http://portal.prattle.co until then. The rollback is being pushed to the servers at the moment, and we should be operating as normal around 2:45 eastern today, the 26th.
